package com.discovery.shortestpathservice.entity;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author SheshidharReddy Amireddy
 */

@Data
@Entity
@NoArgsConstructor
@Slf4j
public class PlanetNames {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    private String planetNode;

    private String planetSourceName;

   /* public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getPlanetNode() {
        return planetNode;
    }

    public void setPlanetNode(String planetNode) {
        this.planetNode = planetNode;
    }

    public String getPlanetSourceName() {
        return planetSourceName;
    }

    public void setPlanetSourceName(String planetName) {
        this.planetSourceName = planetName;
    }*/
   //Getters and Setters generated by Lombok framework

    public PlanetNames(String planetNode, String planetSourceName) {
        this.planetNode = planetNode;
        this.planetSourceName = planetSourceName;
    }

    public static class Builder {

        private String planetNode;
        private String planetSourceName;

        public Builder(){}

        public Builder setPlanetNode(String planetNode) {
            this.planetNode = planetNode;
            return this;
        }

        public Builder setPlanetSourceName(String planetSourceName) {
            this.planetSourceName = planetSourceName;
            return this;
        }

        public PlanetNames build() {
            return new PlanetNames(planetNode, planetSourceName);
        }
    }
}
