package com.discovery.shortestpathservice.model;

import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * @author SheshidharReddy.Amireddy
 */

@Data
@NoArgsConstructor
public class PlanetNamesVO {

    private String planetNode;
    private String planetSourceName;
    private String destinationPlanetName;

    //Getter and Setters generated by Lombok framework


}
